### ISSUE TITLE
finality_provider_info returns response even if the fp doesn't exist

### ISSUE THREAD

**Issue by gusin13** [babylonlabs-io/babylon-contract#68]
One of the FP's below doesn't exist in contract storage but I think contract should return an error instead of success response if FP is not existing in storage. 

```
root@11ff6ff54ba4:/ibcsim-bcd# bcd  q wasm contract-state smart bbnc1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqgn0kq0 '{"finality_provider_info": {"btc_pk_hex":"1eac9bca6174365dec6a814edc588de407364dbad6260babe8dcface7c3448d8"}}'
data:
  btc_pk_hex: 1eac9bca6174365dec6a814edc588de407364dbad6260babe8dcface7c3448d8
  power: 0

```

```
root@11ff6ff54ba4:/ibcsim-bcd# bcd  q wasm contract-state smart bbnc1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqgn0kq0 '{"finality_provider_info": {"btc_pk_hex":"4dada33478a8341c11082ce264a007335d530695e41bf5ddb35ba9e529311887"}}'
data:
  btc_pk_hex: 4dada33478a8341c11082ce264a007335d530695e41bf5ddb35ba9e529311887
  power: 0
```
